# Prod configurations shared by all microservices
spring:
  datasource:
    url: jdbc:oracle:thin:@//<host>:1521/prod-db
    username: prod-username
    password: prod-password
    driver-class-name: oracle.jdbc.OracleDriver
  rabbitmq:
    host: prod-rabbitmq-server
    port: 5999
  redis:
    host: prod-redis-host
    port: 6999
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: update  # or validate for uat/prod

