spring:
  datasource:
    url: jdbc:mysql://prod-db-server:3306/userdb_prod
    username: produser
    password: prodpass
  jpa:
    hibernate:
      ddl-auto: validate
  logging:
    level:
      root: WARN
feature:
  enable-logging: false
  enable-debug-toolbar: false
server:
  port: 8083
